[project]
name = "simulations-workshop-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "blxkex", email = "bhuvanesh7705@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pygame>=2.6.1",
]

[project.scripts]
simulations-workshop-2026 = "simulations_workshop_2026:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
